"""
Hardware lists for 86Box configuration.

Loads from the database generated by parse_86box.py (86box_hardware_db.json).

Load order:
  1. {data_path}/config/86box_hardware_db.json  (runtime-generated, preferred)
  2. app/86box_hardware_db.json                (bundled fallback)
"""

import json
import logging
from functools import lru_cache
from pathlib import Path

log = logging.getLogger("86web.hardware_lists")

_HERE = Path(__file__).parent

# Machine flag constants (from 86Box source)
MACHINE_FLAG_VIDEO      = 0x00000002
MACHINE_FLAG_VIDEO_ONLY = 0x00000008
MACHINE_FLAG_SOUND      = 0x00020000
MACHINE_FLAG_HDC        = 0x0001F100
MACHINE_FLAG_FDC        = 0x00080000
MACHINE_FLAG_NIC        = 0x00100000


@lru_cache(maxsize=1)
def _load() -> dict:
    """Load and return the raw hardware database."""
    paths = []

    # 1. Runtime-generated cache
    try:
        from .config import get_settings
        paths.append(Path(get_settings().data_path) / "config" / "86box_hardware_db.json")
    except Exception:
        pass

    # 2. Bundled fallback (next to this file)
    paths.append(_HERE / "86box_hardware_db.json")

    for p in paths:
        if p.exists():
            log.debug("Loading hardware database from %s", p)
            return json.loads(p.read_text(encoding="utf-8"))

    raise FileNotFoundError(
        "86box_hardware_db.json not found. "
        "It will be generated automatically on first startup."
    )


def reload() -> None:
    """Clear the in-memory cache so the next call re-reads from disk."""
    _load.cache_clear()


# ─── Device list normalisation ────────────────────────────────────────────────

def _norm_config_entry(c: dict) -> dict:
    """Translate raw parser config entry to the schema expected by the frontend."""
    out = dict(c)
    # Strip CONFIG_ prefix and lowercase: CONFIG_HEX16 → hex16
    raw_type = c.get("type", "")
    out["type"] = raw_type.removeprefix("CONFIG_").lower()
    # default_int → default
    if "default_int" in c:
        out["default"] = c["default_int"]
        del out["default_int"]
    # selection → options (frontend expects 'options')
    if "selection" in c:
        out["options"] = c["selection"]
        del out["selection"]
    # spinner.{min,max,step} → spinner_min/max/step
    sp = c.get("spinner")
    if sp and (sp.get("min") or sp.get("max")):
        out["spinner_min"] = sp["min"]
        out["spinner_max"] = sp["max"]
        out["spinner_step"] = sp.get("step", 1)
    if "spinner" in out:
        del out["spinner"]
    # bios entries are complex and not rendered — drop to avoid noise
    out.pop("bios", None)
    return out


def _norm(devices: list[dict]) -> list[dict]:
    """Normalise device list: expose internal_name as 'id', translate config entries."""
    out = []
    for d in devices:
        entry = dict(d)
        entry["id"] = d.get("internal_name", d.get("id", ""))
        if "config" in entry:
            entry["config"] = [_norm_config_entry(c) for c in entry["config"]]
        out.append(entry)
    return out


# ─── Public accessors ─────────────────────────────────────────────────────────

def get_machines() -> list[dict]:
    return _load()["machines"]


def get_cpu_families() -> list[dict]:
    return _load()["cpu_families"]


def get_video_cards() -> list[dict]:
    return _norm(_load()["video_cards"])


def get_sound_cards() -> list[dict]:
    return _norm(_load()["sound_cards"])


def get_network_cards() -> list[dict]:
    return _norm(_load()["network_cards"])


def get_hdc() -> list[dict]:
    """Hard-disk controllers (hdc_1 slot)."""
    return _norm(_load()["hdc"])


def get_scsi() -> list[dict]:
    """SCSI controllers (scsicard_1 slot)."""
    return _norm(_load()["scsi"])


def get_fdc() -> list[dict]:
    """FDC cards (optional add-in FDC)."""
    return _norm(_load()["fdc"])


def get_cdrom_interface() -> list[dict]:
    """CD-ROM interface types."""
    return _norm(_load()["cdrom_interface"])


def get_cdrom_drive_types() -> list[dict]:
    return _load()["cdrom_drive_types"]


def get_hdd_speed_presets() -> list[dict]:
    return _load().get("hdd_speed_presets", [])


def get_isartc() -> list[dict]:
    return _norm(_load()["isartc"])


def get_isamem() -> list[dict]:
    return _norm(_load()["isamem"])


def get_floppy_types() -> list[dict]:
    """Floppy drive type options (parsed from 86Box source)."""
    return _load().get("floppy_types", [])


def get_mouse_types() -> list[dict]:
    """Mouse type options (parsed from 86Box source)."""
    return _load().get("mouse_types", [])


def get_joystick_types() -> list[dict]:
    """Joystick type options (parsed from 86Box source)."""
    return _load().get("joystick_types", [])


# ─── Config-generation helpers ────────────────────────────────────────────────

def machine_has_builtin_video(machine_id: str) -> bool:
    """Return True if this machine has built-in / fixed video."""
    for m in get_machines():
        if m.get("internal_name") == machine_id:
            flags = m.get("flags_value", 0)
            return bool(flags & (MACHINE_FLAG_VIDEO | MACHINE_FLAG_VIDEO_ONLY))
    return False


def get_cpu_by_index(cpu_family_id: str, speed_index: int) -> tuple[int, int]:
    """
    Return (rspeed_hz, multi) for the given cpu_family and speed index.

    rspeed_hz is written as 'cpu_speed' in 86Box cfg.
    multi is written as 'cpu_multi'.

    Falls back to the first CPU in the family, or (4772728, 1) if not found.
    """
    for fam in get_cpu_families():
        if fam.get("internal_name") == cpu_family_id:
            cpus = fam.get("cpus", [])
            if not cpus:
                break
            idx = max(0, min(speed_index, len(cpus) - 1))
            cpu = cpus[idx]
            return (int(cpu.get("rspeed", 4772728)), int(cpu.get("multi", 1)))
    return (4772728, 1)


def get_cpu_families_for_machine(machine_id: str) -> list[dict]:
    """Return CPU families compatible with the given machine."""
    machine = None
    for m in get_machines():
        if m.get("internal_name") == machine_id:
            machine = m
            break
    if machine is None:
        return []

    pkg_set = set(machine.get("cpu_packages", []))
    # A family's package may be a compound string like "CPU_PKG_SOCKET1 | CPU_PKG_SOCKET3_PC330",
    # meaning the CPU fits in any of those sockets. Split and check for any overlap.
    def _family_matches(f: dict) -> bool:
        fam_pkgs = {p.strip() for p in f.get("package", "").split("|")}
        return bool(fam_pkgs & pkg_set)
    return [f for f in get_cpu_families() if _family_matches(f)]


# ─── Legacy shims ──────────────────────────────────────────────────────────────

# Backwards-compat aliases for any remaining code that calls the old names
def get_hdd_controllers() -> list[dict]:
    return get_hdc()

def get_scsi_cards() -> list[dict]:
    return get_scsi()

def get_isartc_types() -> list[dict]:
    return get_isartc()

# These constants are unused but kept so stray imports don't break
MACHINES = None
CPU_FAMILIES = None
VIDEO_CARDS = None
SOUND_CARDS = None
NETWORK_CARDS = None
HDD_CONTROLLERS = None
SCSI_CARDS = None
MOUSE_TYPES = None
JOYSTICK_TYPES = None
